services:
  bot1:
    build: .
    container_name: botnetAlex
    env_file: .env.prod
    restart: unless-stopped

  bot2:
    build: .
    container_name: botnetNico
    env_file: .env.prod2
    restart: unless-stopped
    volumes:
      - botnet_data:/botNet/data

volumes:
  botnet_data:
